name: Build & Unit tests

on:
  push:
    branches: [ "v2", "v2-workflow-tests" ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        os: [ ubuntu-latest ]

    name: Checking
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: go build -v ./...

      - name: Tests
        run: go test -v ./...
